import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Layout from '../components/Layout'
import { useAuthentication } from '../hooks/authentication'
import styles from '../styles/Home.module.css'

export default function Home() {
  const {user} = useAuthentication()

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <p>{user?.uid || '未ログイン'}</p>
          
          <Link href={`/users/${user.uid}`}>
            {user.uid}ぺーじへ遷移する
          </Link>
        </main>
        
        <Link href="/page2">Go to Page2</Link>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </Layout>
  )
}
